language: bash
dist: trusty
group: travis_latest
sudo: required

addons:
  apt:
    packages:
      - docker-ce

branches:
  only:
    - master

env:
  global:
    - BUILD_DATE="`date -u +%Y-%m-%dT%H:%M:%SZ`"
    - BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    - DISTRIB_ID="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'cat /etc/lsb-release') | grep DISTRIB_ID | awk -F '=' {'print $2'}`"
    - DISTRIB_RELEASE="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'cat /etc/lsb-release') | grep DISTRIB_RELEASE | awk -F '=' {'print $2'}`"
    - DISTRIB_CODENAME="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'cat /etc/lsb-release') | grep DISTRIB_CODENAME | awk -F '=' {'print $2'}`"
    - DOCKER_DESCRIPTION="python base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="python"
    - DOCKER_URL="https://www.python.org/"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="`git rev-parse --short HEAD`"
    - VCS_URL="`git remote get-url origin | head -c-5`"
  matrix:
    - DOCKER_TAG="2"
      DOCKER_VERSION="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'apt update -qqq && apt-cache madison openjdk-11-jre-headless') | grep Packages | awk -F '|' {'print $2'} | tr -d ' '`"
    - DOCKER_TAG="3"
      DOCKER_VERSION="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'apt update -qqq && apt-cache madison openjdk-8-jre-headless') | grep Packages | awk -F '|' {'print $2'} | tr -d ' '`"

before_install:
  - docker version
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1

install:
  - sed -i "s/default-jre-headless/openjdk-${DOCKER_TAG}-jre-headless/" Dockerfile

before_script:
  - sed -i -e "/^$/d" -e "s/^[ \t]*//" -e "/^#/d" Dockerfile

script:
  - >
    docker build
    --label org.label-schema.build-date="$BUILD_DATE"
    --label org.label-schema.build-number="$BUILD_NUMBER"
    --label org.label-schema.description="$DOCKER_DESCRIPTION"
    --label org.label-schema.maintainer="$DOCKER_MAINTAINER"
    --label org.label-schema.name="$DOCKER_NAME"
    --label org.label-schema.url="$DOCKER_URL"
    --label org.label-schema.version="$DOCKER_VERSION"
    --label org.label-schema.schema-version="$SCHEMA_VERSION"
    --label org.label-schema.vcs-ref="$VCS_REF"
    --label org.label-schema.vcs-url="$VCS_URL"
    --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}
    --pull .

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

  # Trigger airsonic_docker build
  - >
    if [[ "${DOCKER_TAG}" == "8" ]]; then
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu:rolling", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fairsonic_docker/requests';
    fi

  # Trigger unifi_docker build
  - >
    if [[ "${DOCKER_TAG}" == "8" ]]; then
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu:rolling", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Funifi_docker/requests';
    fi

notifications:
  email:
    on_success: never
    on_failure: change
