language: bash
dist: trusty
group: travis_latest
sudo: required

if: |
  branch = master AND \
  NOT commit_message =~ /readme.md/ AND \
  NOT commit_message =~ /docker-compose.yml/

addons:
  apt:
    packages:
      - docker-ce

stage: build

env:
  global:
    - BUILD_DATE="`date -u +%Y-%m-%dT%H:%M:%SZ`"
    - BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    - DOCKER_DESCRIPTION="python base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="python"
    - DOCKER_URL="https://www.python.org/"
    - SCHEMA_VERSION="1.0"	
    - VCS_REF="`git rev-parse --short HEAD`"	
    - VCS_URL="`git remote get-url origin | head -c-5`"
  matrix:
    - DOCKER_TAG="2"
    - DOCKER_TAG="3"

before_install:
  - docker version
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1

install:

before_script:
  - sed -i -e "/^$/d" -e "s/^[ \t]*//" -e "/^#/d" python${DOCKER_TAG}/Dockerfile

script:
  - docker build --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG} --pull python${DOCKER_TAG}/.

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

jobs:
  include:
    - stage: trigger
      env: DOCKER_TAG=none
      before_install: skip
      install: skip
      before_script: skip
      script:
      # Trigger beets_docker build
      - >
        curl -X POST
        -H "Content-Type: application/json"
        -H "Travis-API-Version: 3"
        -H "Accept: application/json"
        -H "Authorization: token ${TRAVIS_API_TOKEN}"
        -d '{"request": {"message": "Push from stlouisn/python", "branch": "master"}}'
        'https://api.travis-ci.org/repo/stlouisn%2Fbeets_docker/requests'
      # Trigger home-assistant_docker build
      - >
        curl -X POST
        -H "Content-Type: application/json"
        -H "Travis-API-Version: 3"
        -H "Accept: application/json"
        -H "Authorization: token ${TRAVIS_API_TOKEN}"
        -d '{"request": {"message": "Push from stlouisn/python", "branch": "master"}}'
        'https://api.travis-ci.org/repo/stlouisn%2Fhome-assistant_docker/requests'
      after_success: skip

notifications:
  email:
    on_success: never
    on_failure: change
